### ISSUE TITLE
Nice new method

### ISSUE THREAD

**Issue by Welsh-Boogie** [sagishporer/hashcode-2021-qualification#10]
eyy that's nice, also try the Warsa husks one, and yes I noticed, ur recent ones take more time to run and they are using cases not values.

its good, I'm free to run code if u want @sagishporer , I have my pc open all the time with most gpu empty, u can also try multi threading.
 also can u let this thread be open for discussion? thanks. ill look at it when u push the code

**Comment by sagishporer** [comment]
I watched the video. I'm not sure the final algorithm is there. Anyhow, my latest brute force test are beyond those number.

**Comment by Welsh-Boogie** [comment]
> I watched the video. I'm not sure the final algorithm is there. Anyhow, my latest brute force test are beyond those number.

wow, that is the program lol, I made it from the video itsef

**Comment by Welsh-Boogie** [comment]
> I watched the video. I'm not sure the final algorithm is there. Anyhow, my latest brute force test are beyond those number.

would u mind pushing the code or sending it here? i really want to take a look at it, also I'm sorry I am not able to contribute to code itself

**Comment by Welsh-Boogie** [comment]
i have not learnt c# lol sorry

**Comment by Welsh-Boogie** [comment]
@sagishporer u there man?
