### ISSUE TITLE
 Misunderstanding

### ISSUE THREAD

**Issue by Welsh-Boogie** [sagishporer/hashcode-2021-qualification#17]
hi i was not asking u to code, i was goign to code, i was just asking for output for D, the last one or currect one i could use to compare, thanks

**Comment by Welsh-Boogie** [comment]
@sagishporer

**Comment by Welsh-Boogie** [comment]
if u dont want to publically share, upload it on https://app.mediafire.com/ and send the link to download,

**Comment by sagishporer** [comment]
Sure.

I'll commit all the outputs this weekend.

**Comment by Welsh-Boogie** [comment]
> Sure.
> 
> I'll commit all the outputs this weekend.

but studying them would be no use then, cuz after competition ill just run it for delta = 100

**Comment by Welsh-Boogie** [comment]
because we will not be time bound

**Comment by Welsh-Boogie** [comment]
also if u dont want to share please just say so, makes it easier

**Comment by Welsh-Boogie** [comment]
if uu'd liek to know what i will do with it feel free to ask

**Comment by Welsh-Boogie** [comment]
so yeah , if ur sending it, sending it, send it within 1 hour so i have enough time to study it (3-5 hours), then study other cases and try to change, ill try changing in py first then another 3 hours of rewriting in c#

**Comment by Welsh-Boogie** [comment]
@sagishporer

**Comment by Welsh-Boogie** [comment]
atleast respond man, so should i take this as a no?

**Comment by sagishporer** [comment]
I have nothing more to say.
I will publish the output files this weekend.

**Comment by Welsh-Boogie** [comment]
> I have nothing more to say.
> I will publish the output files this weekend.

ok ill take that as a no thanks
