### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by Welsh-Boogie** [sagishporer/hashcode-2021-qualification#18]
what place did u get?

**Comment by sagishporer** [comment]
1

**Comment by Welsh-Boogie** [comment]
> 1

ohh shit nice thats good man great job

**Comment by Welsh-Boogie** [comment]
> 1

also i think all approaches are missing some thing, like it just doesnt fit right

**Comment by sagishporer** [comment]
All the smart things I tried to do failed so I went to hill climbing. I'm sure there are better solutions.

**Comment by Welsh-Boogie** [comment]
> All the smart things I tried to do failed so I went to hill climbing. I'm sure there are better solutions.

yes same could u tell them? i am making the observer too so ill tell u my results

**Comment by Welsh-Boogie** [comment]
> All the smart things I tried to do failed so I went to hill climbing. I'm sure there are better solutions.

i just fail to understand how we need to still see improvement in the greenlight system, we are already doing it to the highest accuracy we can. all I have now is multi-option but without threading or super computer its not even possible

**Comment by Welsh-Boogie** [comment]
only other option is to do code separately in stages

**Comment by sagishporer** [comment]
Actually, on C & E a higher solution was published (CodeForces), but I think I spent too much time on this already.

**Comment by Welsh-Boogie** [comment]
> Actually, on C & E a higher solution was published (CodeForces), but I think I spent too much time on this already.

yes I saw ur update, lol yes true true but we are missing some key thing , one or two that we need to keep in mind that we haven't noticed yet

**Comment by sagishporer** [comment]
I'm sure there are input specific optimizations.

**Comment by Welsh-Boogie** [comment]
> I'm sure there are input specific optimizations.

no the thing I noticed with hashcode is that every input, some key logic needs to be added

**Comment by Welsh-Boogie** [comment]
> I'm sure there are input specific optimizations.

we are missing the key logic for D, E and F because u can see it

**Comment by sagishporer** [comment]
That's why I preferred the main branch. Single algorithm for all.

**Comment by Welsh-Boogie** [comment]
> That's why I preferred the main branch. Single algorithm for all.

yes yes tru also its clean and is applicable in real life

**Comment by Welsh-Boogie** [comment]
> That's why I preferred the main branch. Single algorithm for all.

will people who didn't qualify also get chance to participate in final challenge but like an extended round version of it?

**Comment by sagishporer** [comment]
Don't know. It might be on kaggle like this round.

**Comment by Welsh-Boogie** [comment]
> Don't know. It might be on kaggle like this round.

haven't u don't the competition once before?

**Comment by Welsh-Boogie** [comment]
> Don't know. It might be on kaggle like this round.

would u be working on finals too?

**Comment by sagishporer** [comment]
> would u be working on finals too?

No.

**Comment by Welsh-Boogie** [comment]
> > would u be working on finals too?
> 
> No.

ill send u my solution if I do

**Comment by Welsh-Boogie** [comment]
> > would u be working on finals too?
> 
> No.

are u on codeforcers? is it possible for u to ask the UVIUA Bruteforcers for their outputs?

**Comment by sagishporer** [comment]
Not on CodeForces. 

Don't know. I guess that they'll publish it if they want. It could be they're participating in the Kaggle challenge, so they'll wait untill it's over.

**Comment by Welsh-Boogie** [comment]
> Not on CodeForces.
> 
> Don't know. I guess that they'll publish it if they want. It could be they're participating in the Kaggle challenge, so they'll wait untill it's over.

ok ill tell u my observation result, I'm just curious whats missing

**Comment by Welsh-Boogie** [comment]
> Not on CodeForces.
> 
> Don't know. I guess that they'll publish it if they want. It could be they're participating in the Kaggle challenge, so they'll wait untill it's over.

do u like anything other than competitions in computer programming?
