### ISSUE TITLE
Separate Solutions

### ISSUE THREAD

**Issue by Welsh-Boogie** [sagishporer/hashcode-2021-qualification#4]
Hi @sagishporer , so this is a one for all solution so I was wondering do u know any programs with better individual results or outputs? ill try reverse creating a solution with them, I'm already doing the reversing for an approach with numbers.

**Comment by sagishporer** [comment]
There's a parameter you can set to get better results, it's in the Program.cs, "OptimizeCycleDuration()" method. I wrote the best values I've found in a comment. The highest improvement is in input "F".

**Comment by Welsh-Boogie** [comment]
> There's a parameter you can set to get better results, it's in the Program.cs, "OptimizeCycleDuration()" method. I wrote the best values I've found in a comment. The highest improvement is in input "F".

yes I saw that, its 200 rn, I tried changing it to like 50 and other to like 500

**Comment by Welsh-Boogie** [comment]
@sagishporer something which sorts everything in order of score not just 2 different priority lists but everything will be more precise. https://www.youtube.com/watch?v=15eID397hKU is by the second scorer in qualification round.

**Comment by sagishporer** [comment]
There are few optimization I noticed mentioned in the YouTube video, all of them already performed in the algorithm:
1. Remove unused street.
2. Remove cars not reaching the end.
3. Reorder green lights. 

The difference seems to be in sorting & weight calculations.

**Comment by Welsh-Boogie** [comment]
> There are few optimization I noticed mentioned in the YouTube video, all of them already performed in the algorithm:
> 
> 1. Remove unused street.
> 2. Remove cars not reaching the end.
> 3. Reorder green lights.
> 
> The difference seems to be in sorting & weight calculations.

yeah @sagishporer , like I said in another comment, we need to sort everything, not just 2 lists. we need to make it so best will be go first then others will be left till time runs out, right now we have only done little prioritization, so right now I think adding it so all of them are sorted will do the job, making another cycle of running by swapping position on which goes first like in the pizza approach by you can be done here.
